services:
  - type: web
    name: chattrain-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: chattrain-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: chattrain-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://chattrain-backend.onrender.com/api

databases:
  - name: chattrain-db
    plan: free
